"""Config defaults for DeepSearch report composition (non-LLM markdown + metadata shaping)."""
DEFAULT_EVIDENCE_RANK_ASCII_ANCHOR_MIN = 2
DEFAULT_EVIDENCE_RANK_ASCII_ANCHOR_MAX = 10
DEFAULT_EVIDENCE_RANK_CJK_ANCHOR_MIN = 2
DEFAULT_EVIDENCE_RANK_CJK_ANCHOR_MAX = 6
DEFAULT_EVIDENCE_RANK_MAX_ANCHORS = 24

DEFAULT_DIAGNOSTICS_MAX_KEYS = 24
DEFAULT_DIAGNOSTICS_MAX_VALUE_CHARS = 240
DEFAULT_DIAGNOSTICS_MAX_SMALL_LIST_ITEMS = 8
DEFAULT_DIAGNOSTICS_LIST_ITEM_PREVIEW_CHARS = 80

DEFAULT_CITATION_TOKEN_MAX_CHARS = 64
DEFAULT_ALIAS_SAMPLE_SIZE = 10
DEFAULT_UNKNOWN_ALIAS_SAMPLE_SIZE = 20

DEFAULT_GRAPH_EVIDENCE_SEED_ENTITIES_MAX = 12
DEFAULT_GRAPH_CHAIN_PREVIEW_MAX = 40

DEFAULT_EVIDENCE_PREVIEW_CHARS = 100
DEFAULT_EVIDENCE_PREVIEW_MAX_ITEMS = 40

DEFAULT_EXTERNAL_EVIDENCE_MIN_ITEMS = 2
DEFAULT_EXTERNAL_EVIDENCE_FRACTION_DIVISOR = 3

TOOLISH_CHUNK_ID_PREFIXES: tuple[str, ...] = ("graph.", "tool:")
TOOLISH_SOURCE_NAMES: frozenset[str] = frozenset(
    {
        "context_rollup",
        "evidence_crosscheck",
        "beam_search",
        "parallel_think",
        "think",
    }
)
