"""Default parameters for DeepSearch tools.

These defaults live in `config/` on purpose: core/tool code should not hard-code
search parameters so they can be tuned via configuration and regression runs.
"""

BEAM_SEARCH_DEFAULT_BEAM_SIZE = 3
BEAM_SEARCH_DEFAULT_MAX_DEPTH = 3
BEAM_SEARCH_DEFAULT_TEMPERATURE = 0.2
BEAM_SEARCH_DEFAULT_PATTERN_PROBE_MAX_TERMS = 6

CHUNK_SCAN_DEFAULT_MAX_CHUNKS = 5
CHUNK_SCAN_DEFAULT_QUERY_MAX_CHARS = 240

PATTERN_PROBE_DEFAULT_MAX_TERMS = 4
PATTERN_PROBE_DEFAULT_MIN_LATIN_LENGTH = 4
PATTERN_PROBE_DEFAULT_MIN_CJK_LENGTH = 2

CONTEXT_ROLLUP_DEFAULT_WINDOW_SIZE = 6
CONTEXT_ROLLUP_DEFAULT_SNIPPET_CHARS = 400
CONTEXT_ROLLUP_DEFAULT_TEMPERATURE = 0.0

PARALLEL_THINK_DEFAULT_BRANCHES = 3
PARALLEL_THINK_DEFAULT_TEMPERATURE = 0.4
PARALLEL_THINK_DEFAULT_CONTEXT_PREVIEW_CHARS = 200
PARALLEL_THINK_DEFAULT_CONTEXT_PREVIEW_ITEMS = 3
PARALLEL_THINK_DEFAULT_CONFIDENCE_DELTA_PER_BRANCH = 0.1
PARALLEL_THINK_DEFAULT_COVERAGE_DELTA_PER_BRANCH = 0.05

HYBRID_NEIGHBORHOOD_DEFAULT_MAX_CHUNKS = 5
HYBRID_NEIGHBORHOOD_DEFAULT_PATTERN_MAX_TERMS = 3
HYBRID_NEIGHBORHOOD_DEFAULT_TRAVERSAL_STRATEGY = "ppr_chain"
HYBRID_NEIGHBORHOOD_DEFAULT_TRAVERSAL_MAX_DEPTH = 2
HYBRID_NEIGHBORHOOD_DEFAULT_SNIPPET_CHARS = 400
HYBRID_NEIGHBORHOOD_DEFAULT_SUMMARY_TEMPERATURE = 0.1

# -----------------------------
# graph.think tool defaults
# -----------------------------
THINK_JSON_REPAIR_DEFAULT_ATTEMPTS = 1
THINK_JSON_REPAIR_DEFAULT_TEMPERATURE = 0.0
THINK_JSON_REPAIR_DEFAULT_MAX_RAW_CHARS = 2000

# -----------------------------
# code.python tool defaults
# -----------------------------
# Keep this list small and finance-focused; expand via config when needed.
CODE_PYTHON_DEFAULT_ALLOWED_IMPORTS = (
    "json",
    "math",
    "decimal",
    "fractions",
    "statistics",
    "datetime",
    "numpy",
    "pandas",
    "scipy",
)

CODE_PYTHON_DEFAULT_TIMEOUT_SECONDS = 6.0
CODE_PYTHON_DEFAULT_MAX_CODE_CHARS = 12000
CODE_PYTHON_DEFAULT_MAX_STDOUT_CHARS = 8000
CODE_PYTHON_DEFAULT_MAX_STDERR_CHARS = 8000
CODE_PYTHON_DEFAULT_MAX_RESULT_CHARS = 12000
CODE_PYTHON_DEFAULT_MAX_MEMORY_MB = 1024
CODE_PYTHON_DEFAULT_EMIT_RESULT_EVIDENCE = True

# Internal output/diagnostics knobs (kept here to avoid scattered thresholds).
CODE_PYTHON_MIN_TIMEOUT_SECONDS = 0.1
CODE_PYTHON_SUMMARY_PREVIEW_CHARS = 240
CODE_PYTHON_BAD_RUNNER_STDOUT_PREVIEW_CHARS = 800
CODE_PYTHON_BAD_RUNNER_STDERR_PREVIEW_CHARS = 800
CODE_PYTHON_RUNNER_STDERR_PREVIEW_CHARS = 1200
CODE_PYTHON_TRACEBACK_LIMIT = 8
