EXTRACTION_ERROR_KEY = "extraction_error"
EXTRACTION_SKIPPED_KEY = "extraction_skipped"
MINDMAP_ERROR_KEY = "mindmap_error"
TEMPORAL_ERROR_KEY = "temporal_error"
BUSINESS_TIME_KEY = "business_time"
SDF_KEY = "sdf"
SDF_HS_KEY = "sdf_hs"
SDF_ERROR_KEY = "sdf_error"
