"""Prompt templates specific to DeepSearch pipelines."""

from .plan import GRAPH_PLANNER_SYSTEM_PROMPT, GRAPH_PLANNER_USER_PROMPT
from .tools import (
    CONTEXT_ROLLUP_PROMPT,
    CONTEXT_REWRITER_PROMPT,
    EVIDENCE_CROSSCHECK_PROMPT,
    LLM_CHAIN_EXPLORER_SYSTEM_PROMPT,
    HYBRID_NEIGHBORHOOD_SUMMARY_PROMPT,
    PARALLEL_THINK_SYSTEM_PROMPT,
    THINK_TOOL_SYSTEM_PROMPT,
)

__all__ = [
    "GRAPH_PLANNER_SYSTEM_PROMPT",
    "GRAPH_PLANNER_USER_PROMPT",
    "EVIDENCE_CROSSCHECK_PROMPT",
    "LLM_CHAIN_EXPLORER_SYSTEM_PROMPT",
    "CONTEXT_ROLLUP_PROMPT",
    "CONTEXT_REWRITER_PROMPT",
    "THINK_TOOL_SYSTEM_PROMPT",
    "PARALLEL_THINK_SYSTEM_PROMPT",
    "HYBRID_NEIGHBORHOOD_SUMMARY_PROMPT",
]
