"""Prompt templates specific to DeepSearch pipelines."""

from .plan import GRAPH_PLANNER_SYSTEM_PROMPT, GRAPH_PLANNER_USER_PROMPT
from .heavy_tools import BEAM_SEARCH_RERANK_SYSTEM_PROMPT_V1
from .runtime import TRACE_REFLECTION_SYSTEM_PROMPT_TEMPLATE, TRACE_REFLECTION_USER_PROMPT_TEMPLATE
from .tools import (
    LLM_CHAIN_EXPLORER_SYSTEM_PROMPT,
    SEARCH_ENTITY_EXTRACT_PROMPT,
    THINK_TOOL_SYSTEM_PROMPT,
)
from .bench_answer import (
    DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_EN,
    DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_STRICT_EN,
    DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_COVERAGE_EN,
    DEEPSEARCH_BENCH_ANSWER_USER_PROMPT_TEMPLATE_EN,
    DEEPSEARCH_BENCH_EXTRACT_SYSTEM_PROMPT_EN,
    DEEPSEARCH_BENCH_EXTRACT_USER_PROMPT_TEMPLATE_EN,
    DEEPSEARCH_BENCH_FINAL_SYSTEM_PROMPT_EN,
    DEEPSEARCH_BENCH_FINAL_USER_PROMPT_TEMPLATE_EN,
)

__all__ = [
    "GRAPH_PLANNER_SYSTEM_PROMPT",
    "GRAPH_PLANNER_USER_PROMPT",
    "BEAM_SEARCH_RERANK_SYSTEM_PROMPT_V1",
    "TRACE_REFLECTION_SYSTEM_PROMPT_TEMPLATE",
    "TRACE_REFLECTION_USER_PROMPT_TEMPLATE",
    "LLM_CHAIN_EXPLORER_SYSTEM_PROMPT",
    "THINK_TOOL_SYSTEM_PROMPT",
    "SEARCH_ENTITY_EXTRACT_PROMPT",
    "DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_EN",
    "DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_STRICT_EN",
    "DEEPSEARCH_BENCH_ANSWER_SYSTEM_PROMPT_COVERAGE_EN",
    "DEEPSEARCH_BENCH_ANSWER_USER_PROMPT_TEMPLATE_EN",
    "DEEPSEARCH_BENCH_EXTRACT_SYSTEM_PROMPT_EN",
    "DEEPSEARCH_BENCH_EXTRACT_USER_PROMPT_TEMPLATE_EN",
    "DEEPSEARCH_BENCH_FINAL_SYSTEM_PROMPT_EN",
    "DEEPSEARCH_BENCH_FINAL_USER_PROMPT_TEMPLATE_EN",
]
